# Generated by Django 3.1.7 on 2021-03-31 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='distributors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distributor_id', models.CharField(max_length=256)),
                ('name', models.CharField(max_length=256)),
                ('last_update', models.DateField()),
                ('registration_date', models.DateField()),
                ('update_count', models.IntegerField(default=0)),
                ('rating', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line', models.CharField(max_length=256)),
                ('zip_code', models.CharField(default='30332', max_length=12)),
                ('city', models.CharField(default='Atlanta', max_length=256)),
                ('state', models.CharField(default='Georgia', max_length=256)),
                ('country', models.CharField(default='US', max_length=256)),
                ('distributor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='distributors.distributors')),
            ],
        ),
    ]
