# Generated by Django 3.1.7 on 2021-03-31 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('distributors', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='distributor_id',
            new_name='distributors',
        ),
    ]
