# Generated by Django 3.1.7 on 2021-03-31 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributors', '0002_auto_20210331_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributors',
            name='address_line',
            field=models.CharField(default='842 Peachtree St NE', max_length=256),
        ),
        migrations.AddField(
            model_name='distributors',
            name='city',
            field=models.CharField(default='Atlanta', max_length=256),
        ),
        migrations.AddField(
            model_name='distributors',
            name='country',
            field=models.CharField(default='US', max_length=256),
        ),
        migrations.AddField(
            model_name='distributors',
            name='state',
            field=models.CharField(default='Georgia', max_length=256),
        ),
        migrations.AddField(
            model_name='distributors',
            name='zip_code',
            field=models.CharField(default='30308', max_length=12),
        ),
        migrations.DeleteModel(
            name='address',
        ),
    ]
