# Generated by Django 3.1.7 on 2021-04-06 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('physicians', '0002_auto_20210406_1455'),
        ('distributors', '0003_auto_20210331_1547'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='distributors',
            name='id',
        ),
        migrations.AddField(
            model_name='distributors',
            name='physicians',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='physicians.physicians'),
        ),
        migrations.AlterField(
            model_name='distributors',
            name='distributor_id',
            field=models.CharField(max_length=256, primary_key=True, serialize=False),
        ),
    ]
