# Generated by Django 3.1.7 on 2021-04-06 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('physicians', '0004_auto_20210406_1625'),
        ('distributors', '0010_auto_20210406_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distributors',
            name='physicians',
            field=models.ForeignKey(default='', editable=False, on_delete=django.db.models.deletion.RESTRICT, to='physicians.physicians'),
        ),
    ]
