# Generated by Django 3.1.7 on 2021-04-06 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('physicians', '0005_auto_20210406_1626'),
        ('distributors', '0011_auto_20210406_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distributors',
            name='physicians',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='physicians.physicians'),
        ),
    ]
