# Generated by Django 3.1.7 on 2021-04-06 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributors', '0013_remove_distributors_physicians'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='distributors',
            name='distributor_id',
        ),
        migrations.AddField(
            model_name='distributors',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
