# Generated by Django 3.1.7 on 2021-04-06 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributors', '0014_auto_20210406_1637'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='distributors',
            name='id',
        ),
        migrations.AddField(
            model_name='distributors',
            name='distributor_id',
            field=models.CharField(default=None, max_length=256, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
