# Generated by Django 3.1.7 on 2021-04-09 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('physicians', '0009_auto_20210406_1637'),
        ('distributors', '0015_auto_20210406_1637'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='distributors',
            new_name='distributor',
        ),
    ]
