# Generated by Django 3.1.7 on 2021-04-06 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=256)),
                ('password', models.CharField(max_length=256)),
                ('first_name', models.CharField(max_length=256)),
                ('last_name', models.CharField(max_length=256)),
                ('age', models.IntegerField(default=0)),
                ('preexisting', models.CharField(max_length=256)),
                ('occupation', models.CharField(max_length=256)),
                ('living_situation', models.CharField(max_length=256)),
                ('priority', models.CharField(default='low', max_length=256)),
            ],
        ),
    ]
