# Generated by Django 3.1.7 on 2021-04-10 13:43

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('is_patient', models.BooleanField(default=False)),
                ('is_physician', models.BooleanField(default=False)),
                ('is_distributor', models.BooleanField(default=False)),
                ('address_line', models.CharField(default='842 Peachtree St NE', max_length=256)),
                ('zip_code', models.CharField(default='30308', max_length=12)),
                ('city', models.CharField(default='Atlanta', max_length=256)),
                ('state', models.CharField(default='Georgia', max_length=256)),
                ('country', models.CharField(default='US', max_length=256)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Vaccine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccine_id', models.CharField(max_length=256)),
                ('brand', models.CharField(max_length=256)),
                ('dose_required', models.IntegerField(default=2)),
                ('if_used', models.BooleanField(default=False)),
                ('expiration_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Distributor',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='user.account')),
                ('name', models.CharField(max_length=256)),
                ('last_update', models.DateField()),
                ('registration_date', models.DateField()),
                ('update_count', models.IntegerField(default=0)),
                ('rating', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='user.account')),
                ('first_name', models.CharField(max_length=256)),
                ('last_name', models.CharField(max_length=256)),
                ('age', models.IntegerField(default=0)),
                ('preexisting', multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Cancer'), (2, 'Cerebrovascular disease'), (3, 'Chronic kidney disease'), (4, 'COPD'), (5, 'Diabetes mellitus, type 1'), (6, 'Diabetes mellitus, type 2'), (7, 'Heart conditions'), (8, 'Smoking'), (9, 'Obesity'), (10, 'Pregnancy'), (11, 'Down syndrome'), (12, 'HIV'), (13, 'Neurologic conditions'), (14, 'Overweight'), (15, 'Lung disease'), (16, 'Sickle cell disease'), (17, 'Solid organ or blood stem cell transplantation'), (18, 'Substance use disorders'), (19, 'Cystic fibrosis'), (20, 'Neurologic conditions'), (21, 'Thalassemia'), (22, 'Asthma'), (23, 'Hypertension'), (24, 'Liver disease'), (25, 'Immune Deficiencies')], default=None, max_length=65)),
                ('occupation', multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Agriculture'), (2, 'Clothing Industry'), (3, 'Computer Science/ IT'), (4, 'Construction'), (5, 'Education'), (6, 'Entertainment'), (7, 'Finance/ Accounting'), (8, 'First Responder'), (9, 'Food Services'), (10, 'Government Employee'), (11, 'Law'), (12, 'Medical Field'), (13, 'Military'), (14, 'Other (In-person)'), (15, 'Other (Virtual)')], default=None, max_length=35)),
                ('living_situation', multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Independent (1 person)'), (2, 'Small Group (2-6)'), (3, 'Small Group Housing (7 - 20)'), (4, 'Large Group Housing (21+)'), (5, 'Assisted Living'), (6, 'Live with someone that is at risk')], default=None, max_length=11)),
                ('priority', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Physician',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='user.account')),
                ('first_name', models.CharField(default=None, max_length=256)),
                ('last_name', models.CharField(default=None, max_length=256)),
                ('distributor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='user.distributor')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startTime', models.DateTimeField()),
                ('endTime', models.DateTimeField()),
                ('vaccineName', models.CharField(default='Pfizer', max_length=256)),
                ('dose', models.IntegerField(default=1)),
                ('currphysician', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='user.physician')),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='user.patient')),
            ],
            options={
                'unique_together': {('currphysician', 'patient')},
            },
        ),
    ]
