# Generated by Django 3.1.7 on 2021-04-10 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distributor',
            name='last_update',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='distributor',
            name='rating',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='distributor',
            name='registration_date',
            field=models.DateField(null=True),
        ),
    ]
