# Generated by Django 3.1.7 on 2021-04-07 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210406_1455'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreexistingChoices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=300)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='preexisting',
        ),
        migrations.AddField(
            model_name='user',
            name='preexisting',
            field=models.ManyToManyField(to='user.PreexistingChoices'),
        ),
    ]
