# Generated by Django 3.1.7 on 2021-04-10 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210410_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distributor',
            name='last_update',
            field=models.DateField(default='2021-04-10'),
        ),
        migrations.AlterField(
            model_name='distributor',
            name='rating',
            field=models.FloatField(default=5),
        ),
        migrations.AlterField(
            model_name='distributor',
            name='registration_date',
            field=models.DateField(default='2021-04-10'),
        ),
    ]
