# Generated by Django 3.1.7 on 2021-04-07 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20210407_1412'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='preexisting',
        ),
        migrations.DeleteModel(
            name='PreexistingChoices',
        ),
    ]
