# Generated by Django 3.1.7 on 2021-04-10 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20210410_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distributor',
            name='last_update',
            field=models.DateField(),
        ),
    ]
