# Generated by Django 3.1.7 on 2021-04-07 18:28

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20210407_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='preexisting',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Cancer'), (2, 'COPDs')], default=None, max_length=3),
            preserve_default=False,
        ),
    ]
