# Generated by Django 3.1.7 on 2021-04-09 19:48

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20210407_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='living_situation',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Independent (1 person)'), (2, 'Small Group (2-6)'), (3, 'Small Group Housing (7 - 20)'), (4, 'Large Group Housing (21+)'), (5, 'Assisted Living'), (6, 'Live with someone that is at risk')], default=None, max_length=11),
        ),
        migrations.AlterField(
            model_name='user',
            name='occupation',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Agriculture'), (2, 'Clothing Industry'), (3, 'Computer Science/ IT'), (4, 'Construction'), (5, 'Education'), (6, 'Entertainment'), (7, 'Finance/ Accounting'), (8, 'First Responder'), (9, 'Food Services'), (10, 'Government Employee'), (11, 'Law'), (12, 'Medical Field'), (13, 'Military'), (14, 'Other (In-person)'), (15, 'Other (Virtual)')], default=None, max_length=35),
        ),
        migrations.AlterField(
            model_name='user',
            name='preexisting',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Cancer'), (2, 'Cerebrovascular disease'), (3, 'Chronic kidney disease'), (4, 'COPD'), (5, 'Diabetes mellitus, type 1'), (6, 'Diabetes mellitus, type 2'), (7, 'Heart conditions'), (8, 'Smoking'), (9, 'Obesity'), (10, 'Pregnancy'), (11, 'Down syndrome'), (12, 'HIV'), (13, 'Neurologic conditions'), (14, 'Overweight'), (15, 'Lung disease'), (16, 'Sickle cell disease'), (17, 'Solid organ or blood stem cell transplantation'), (18, 'Substance use disorders'), (19, 'Cystic fibrosis'), (20, 'Neurologic conditions'), (21, 'Thalassemia'), (22, 'Asthma'), (23, 'Hypertension'), (24, 'Liver disease'), (25, 'Immune Deficiencies')], default=None, max_length=65),
        ),
    ]
