# Generated by Django 3.1.7 on 2021-04-14 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20210410_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='address_line',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='account',
            name='city',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='account',
            name='country',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='account',
            name='state',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='account',
            name='zip_code',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='vaccineName',
            field=models.OneToOneField(max_length=256, on_delete=django.db.models.deletion.RESTRICT, to='user.vaccine'),
        ),
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together={('currphysician', 'patient', 'vaccineName')},
        ),
    ]
