# Generated by Django 3.1.7 on 2021-04-14 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20210414_1425'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(fields=('currphysician', 'patient', 'vaccineName'), name='name of constraint'),
        ),
    ]
