# Generated by Django 3.1.7 on 2021-04-14 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_auto_20210414_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='physician',
            name='distributor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, to='user.distributor'),
        ),
    ]
