# Generated by Django 3.1.7 on 2021-04-15 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_auto_20210415_0131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physician',
            name='distributor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.distributor'),
        ),
    ]
