# Generated by Django 3.1.7 on 2021-04-15 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_auto_20210415_0152'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='endTime',
            new_name='end_time',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='currphysician',
            new_name='physician',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='startTime',
            new_name='start_time',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='vaccineName',
            new_name='vaccine_name',
        ),
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together={('physician', 'patient', 'vaccine_name')},
        ),
    ]
