# Generated by Django 3.1.7 on 2021-04-15 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_auto_20210415_0224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='patient',
            field=models.OneToOneField(blank=True, default=None, on_delete=django.db.models.deletion.RESTRICT, to='user.patient'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='physician',
            field=models.OneToOneField(blank=True, default=None, on_delete=django.db.models.deletion.RESTRICT, to='user.physician'),
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='dose_required',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='if_used',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
