# Generated by Django 3.1.7 on 2021-04-15 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0022_auto_20210415_1210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='priority',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patient',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.patient'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='physician',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.physician'),
        ),
    ]
