# Generated by Django 3.1.7 on 2021-04-15 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_auto_20210415_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='distributor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='user.distributor'),
        ),
    ]
