# Generated by Django 3.1.7 on 2021-04-16 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0024_appointment_distributor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaccine',
            name='if_used',
        ),
    ]
