# Generated by Django 3.1.7 on 2021-04-06 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_auto_20210406_1455'),
        ('physicians', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='physicians',
            fields=[
                ('username', models.CharField(default=None, max_length=256, primary_key=True, serialize=False)),
                ('first_name', models.CharField(default=None, max_length=256)),
                ('last_name', models.CharField(default=None, max_length=256)),
            ],
        ),
        migrations.DeleteModel(
            name='physician',
        ),
    ]
