# Generated by Django 3.1.7 on 2021-04-06 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('physicians', '0002_auto_20210406_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physicians',
            name='username',
            field=models.CharField(default='doctor1', max_length=256, primary_key=True, serialize=False),
        ),
    ]
