# Generated by Django 3.1.7 on 2021-04-06 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('physicians', '0003_auto_20210406_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='physicians',
            name='id',
            field=models.AutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='physicians',
            name='username',
            field=models.CharField(default='', editable=False, max_length=256, unique=True),
        ),
    ]
