# Generated by Django 3.1.7 on 2021-04-06 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('physicians', '0004_auto_20210406_1625'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='physicians',
            name='id',
        ),
        migrations.AlterField(
            model_name='physicians',
            name='username',
            field=models.CharField(max_length=256, primary_key=True, serialize=False),
        ),
    ]
