# Generated by Django 3.1.7 on 2021-04-06 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('distributors', '0013_remove_distributors_physicians'),
        ('physicians', '0005_auto_20210406_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='physicians',
            name='distributor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, to='distributors.distributors'),
            preserve_default=False,
        ),
    ]
