# Generated by Django 3.1.7 on 2021-04-06 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('distributors', '0014_auto_20210406_1637'),
        ('physicians', '0007_auto_20210406_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physicians',
            name='distributor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='distributors.distributors'),
        ),
    ]
