# Generated by Django 3.1.7 on 2021-04-09 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('distributors', '0016_auto_20210409_1543'),
        ('appointments', '0003_auto_20210406_1645'),
        ('physicians', '0009_auto_20210406_1637'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='physicians',
            new_name='physician',
        ),
    ]
