# Generated by Django 3.1.7 on 2021-04-06 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('physicians', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='appointments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startTime', models.DateTimeField()),
                ('endTime', models.DateTimeField()),
                ('vaccineName', models.CharField(default='Pfizer', max_length=256)),
                ('dose', models.IntegerField(default=1)),
                ('currphysician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='physicians.physician')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
