# Generated by Django 3.1.7 on 2021-04-06 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointments',
            name='currphysician',
        ),
        migrations.RemoveField(
            model_name='appointments',
            name='patient',
        ),
    ]
