# Generated by Django 3.1.7 on 2021-04-06 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('physicians', '0009_auto_20210406_1637'),
        ('user', '0002_auto_20210406_1455'),
        ('appointments', '0002_auto_20210406_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='currphysician',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.RESTRICT, to='physicians.physicians'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointments',
            name='patient',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.RESTRICT, to='user.user'),
            preserve_default=False,
        ),
    ]
