# Generated by Django 3.1.7 on 2021-04-09 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('physicians', '0010_auto_20210409_1547'),
        ('user', '0007_auto_20210409_1548'),
        ('appointments', '0003_auto_20210406_1645'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='appointments',
            new_name='appointment',
        ),
    ]
