# Generated by Django 3.1.7 on 2021-03-31 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='vaccine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccine_id', models.FloatField()),
                ('brand', models.CharField(max_length=256)),
                ('dose_required', models.IntegerField(default=2)),
                ('if_used', models.BooleanField(default=False)),
                ('expiration_date', models.DateField()),
            ],
        ),
    ]
